---
abstract: 'declarative testing'
author:
  - 'Atsushi Kobayashi  C<< <nekokak __at__ gmail.com> >>'
build_requires:
  Test::Builder: 0
  Test::More: 0
  Test::Tester: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Declare
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  Filter::Util::Call: 0
  IO::Scalar: 0
  PPI: 0
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0
  Test::Output: 0
  Test::Warn: 0
  xt: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
